export default {
  Apps: "assets/code-tags.svg",
  Articles: "assets/pencil.svg",
  Awards: "assets/ribbon.svg",
  Books: "assets/library.svg",
  Culture: "assets/palette.svg",
  Economic: "assets/currency-usd.svg",
  Education: "assets/school.svg",
  Employment: "assets/briefcase.svg",
  Environment: "assets/bee-flower.svg",
  Events: "assets/calendar.svg",
  Hacks: "assets/code-tags.svg",
  Medical: "assets/heart-pulse.svg",
  News: "assets/newspaper.svg",
  OKR: "assets/chart-pie.svg",
  Patents: "assets/bank.svg",
  Projects: "assets/memory.svg",
  Publications: "assets/book.svg",
  Social: "assets/human-male-female.svg",
  Standards: "assets/ballot.svg",
  Technology: "assets/monitor-cellphone.svg",
  Videos: "assets/video.svg"
} as Record<string, string>
