export default [
  {
      "link": "mailto:nickfelker+nickswebsite@gmail.com",
      "type": "E-Mail",
      "icon": "assets/email.svg"
  }, {
      "link": "http://twitter.com/handnf",
      "type": "Twitter",
      "icon": "assets/twitter.svg"
  }, {
      "link": "https://instagram.com/fleker",
      "type": "Instagram",
      "icon": "assets/instagram.svg"
  }, {
      "link": "https://www.linkedin.com/in/nickfelker",
      "type": "LinkedIn",
      "icon": "assets/linkedin.svg"
  }, {
      "link": "https://soundcloud.com/nick-felker-1",
      "type": "Soundcloud",
      "icon": "assets/soundcloud.svg"
  }, {
      "link": "https://medium.com/@fleker",
      "type": "Medium",
      "icon": "assets/medium.svg"
  }, {
      "link": "https://github.com/fleker",
      "type": "GitHub",
      "icon": "assets/github-circle.svg"
  }, {
      "link": "https://open.spotify.com/user/12495681",
      "type": "Spotify",
      "icon": "assets/spotify.svg"
  }, {
      "link": "https://kickstarter.com/profile/186762105",
      "type": "Kickstarter",
      "icon": "assets/kickstarter.svg"
  }, {
      "link": "https://goodreads.com/user/show/5246265-nick",
      "type": "Goodreads",
      "icon": "assets/goodreads.svg"
  }, {
      "link": "https://www.youtube.com/channel/UCsqcEY-4h9tQQJuGlCLPLSA",
      "type": "YouTube",
      "icon": "assets/youtube-play.svg"
  }, {
      "link": "https://www.tiktok.com/@fleker",
      "type": "Tiktok",
      "icon": "assets/tiktok.svg"
  }, {
      "link": "https://letterboxd.com/fleker/",
      "type": "Letterboxd",
      "icon": "assets/movie.svg"
  }, {
    "link": "https://mastodon.world/@fleker",
    "type": "Mastodon",
    "icon": "assets/mastodon.svg"
  }, {
    "link": "https://pokedextracker.com/u/fleker/",
    "type": "PokéDex Tracker",
    "icon": "assets/pokemon-go.svg"
  },
]